<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitXMLReporter -->
<testsuite hostname="DESKTOP-CFDBD86" ignored="9" name="CromeTest" tests="10" failures="6" timestamp="22 Aug 2019 14:32:03 GMT" time="324.184" errors="0">
  <testcase name="sanityTest" time="58.182" classname="tests.SanityTest"/>
  <testcase name="QinAnotherLang" time="17.746" classname="tests.ErrorHTests">
    <failure type="java.lang.AssertionError" message="Error message didn&amp;apos;t show - no error message when question is not in english expected [true] but found [false]">
      <![CDATA[java.lang.AssertionError: Error message didn't show - no error message when question is not in english expected [true] but found [false]
at tests.ErrorHTests.QinAnotherLang(ErrorHTests.java:350)
at java.util.concurrent.FutureTask.run(Unknown Source)
at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
at java.lang.Thread.run(Unknown Source)
... Removed 19 stack frames]]>
    </failure>
  </testcase> <!-- QinAnotherLang -->
  <testcase name="answerNotChecked" time="14.29" classname="tests.ErrorHTests"/>
  <testcase name="answersAfterLastQBack" time="39.835" classname="tests.ErrorHTests">
    <failure type="java.lang.AssertionError" message="The following asserts failed:
	This is not question 2 screen expected [true] but found [false]">
      <![CDATA[java.lang.AssertionError: The following asserts failed:
This is not question 2 screen expected [true] but found [false]
at tests.ErrorHTests.answersAfterLastQBack(ErrorHTests.java:741)
at java.util.concurrent.FutureTask.run(Unknown Source)
at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
at java.lang.Thread.run(Unknown Source)
... Removed 17 stack frames]]>
    </failure>
  </testcase> <!-- answersAfterLastQBack -->
  <testcase name="changeAnswerInSetup" time="23.418" classname="tests.ErrorHTests"/>
  <testcase name="lastQback42Q" time="41.726" classname="tests.ErrorHTests">
    <failure type="java.lang.AssertionError" message="The following asserts failed:
	This is not question 2 screen expected [true] but found [false],
	This is not question 2 screen expected [true] but found [false]">
      <![CDATA[java.lang.AssertionError: The following asserts failed:
This is not question 2 screen expected [true] but found [false],
This is not question 2 screen expected [true] but found [false]
at tests.ErrorHTests.lastQback42Q(ErrorHTests.java:577)
at java.util.concurrent.FutureTask.run(Unknown Source)
at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
at java.lang.Thread.run(Unknown Source)
... Removed 17 stack frames]]>
    </failure>
  </testcase> <!-- lastQback42Q -->
  <testcase name="numberAsAnswer" time="25.14" classname="tests.ErrorHTests">
    <failure type="java.lang.AssertionError" message="Error message didn&amp;apos;t show - no error message when answer is not in characters alone expected [true] but found [false]">
      <![CDATA[java.lang.AssertionError: Error message didn't show - no error message when answer is not in characters alone expected [true] but found [false]
at tests.ErrorHTests.numberAsAnswer(ErrorHTests.java:174)
at java.util.concurrent.FutureTask.run(Unknown Source)
at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
at java.lang.Thread.run(Unknown Source)
... Removed 19 stack frames]]>
    </failure>
  </testcase> <!-- numberAsAnswer -->
  <testcase name="overMaxCharsQ" time="7.868" classname="tests.ErrorHTests">
    <failure type="java.lang.AssertionError" message="Error message didn&amp;apos;t show - no error message when max characters in question is over 50 expected [true] but found [false]">
      <![CDATA[java.lang.AssertionError: Error message didn't show - no error message when max characters in question is over 50 expected [true] but found [false]
at tests.ErrorHTests.overMaxCharsQ(ErrorHTests.java:105)
at java.util.concurrent.FutureTask.run(Unknown Source)
at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
at java.lang.Thread.run(Unknown Source)
... Removed 19 stack frames]]>
    </failure>
  </testcase> <!-- overMaxCharsQ -->
  <testcase name="overMzxCharA" time="19.052" classname="tests.ErrorHTests"/>
  <testcase name="skipFillingAQuestion" time="26.493" classname="tests.ErrorHTests">
    <failure type="java.lang.AssertionError" message="Error message didn&amp;apos;t show - A question wasn&amp;apos;t inserted expected [true] but found [false]">
      <![CDATA[java.lang.AssertionError: Error message didn't show - A question wasn't inserted expected [true] but found [false]
at tests.ErrorHTests.skipFillingAQuestion(ErrorHTests.java:319)
at java.util.concurrent.FutureTask.run(Unknown Source)
at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
at java.lang.Thread.run(Unknown Source)
... Removed 19 stack frames]]>
    </failure>
  </testcase> <!-- skipFillingAQuestion -->
  <testcase name="selectAnswer24EachQ" time="0.0" classname="tests.FuncTests">
    <ignored/>
  </testcase> <!-- selectAnswer24EachQ -->
  <testcase name="selectAnswer44EachQ" time="0.0" classname="tests.FuncTests">
    <ignored/>
  </testcase> <!-- selectAnswer44EachQ -->
  <testcase name="quitAfterSetup" time="0.0" classname="tests.FuncTests">
    <ignored/>
  </testcase> <!-- quitAfterSetup -->
  <testcase name="addQmarkAutomaticlly" time="0.0" classname="tests.FuncTests">
    <ignored/>
  </testcase> <!-- addQmarkAutomaticlly -->
  <testcase name="tryAgain" time="0.0" classname="tests.FuncTests">
    <ignored/>
  </testcase> <!-- tryAgain -->
  <testcase name="selectAnswerVar4EachQ" time="0.0" classname="tests.FuncTests">
    <ignored/>
  </testcase> <!-- selectAnswerVar4EachQ -->
  <testcase name="selectAnswer34EachQ" time="0.0" classname="tests.FuncTests">
    <ignored/>
  </testcase> <!-- selectAnswer34EachQ -->
  <testcase name="back2PrevQ" time="0.0" classname="tests.FuncTests">
    <ignored/>
  </testcase> <!-- back2PrevQ -->
  <testcase name="quitGame" time="0.0" classname="tests.FuncTests">
    <ignored/>
  </testcase> <!-- quitGame -->
</testsuite> <!-- CromeTest -->
